### PR TITLE
Trivial PyQt5 support

### PR DESCRIPTION
**Pull request by 4gra**
I had to port this to work with Qt5, so I thought I'd share the minimal changes required.

### CODE REVIEW

**Comment by 4gra** [comment]
I know it's a bit cheeky just renaming the import! It's not extensively tested but I thought it'd make the point to onlookers that it's basically already compatible. I noticed a few tiny changes, behaviour following 'load' then 'cancel' seemed a little different, quitting the application. But a basic test worked.

**Comment by 4gra** [comment]
Apologies - I don't know how I missed the four-year old pull request in which this was first fixed ...

**Comment by shimpe** [comment]
No problem, but back then I was hoping it would be made compatible with both PyQt4 and PyQt5. I still think that shouldn't be too hard. In the mean time I don't use it myself anymore, so I have to admit I kind of forgot about the previous pull request too!

**Comment by 4gra** [comment]
I'll take a look. What would you prefer? 5 with fallback to 4? Vice verse? Or active choice?

**Comment by shimpe** [comment]
5 with fallback to 4 is fine, nowadays I guess we should start thinking about 6 as well? :)

**Pull request closed without merging**
